version: "3"
services:
  food_app: 
    environment:
      - PYTHONUNBUFFERED=0
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
    #   # Uncomment For Test in venv
    #   # - SQLALCHEMY_DATABASE_URI = sqlite:///test_db.sqlite
    
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - postgres

  redis:
      image: redis
      ports:
        - 6378:6379

  postgres:
      container_name: postgres
      image: postgres:latest
      restart: always
      ports:
        - 5431:5431
      environment:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_HOST=$POSTGRES_HOST
        - POSTGRES_PORT=$POSTGRES_PORT
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_HOST_AUTH_METHOD=trust




    